"""update_fortune_logs_schema

Revision ID: 17bbc240bbf3
Revises: 97955fa98cae
Create Date: 2026-04-17 19:09:28.880272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bbc240bbf3'
down_revision: Union[str, Sequence[str], None] = '97955fa98cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_fortunes', sa.Column('status', sa.String(length=10), server_default='SUCCESS', nullable=False))
    op.add_column('daily_fortunes', sa.Column('error_msg', sa.Text(), nullable=True))
    op.add_column('fortune_logs', sa.Column('model_name', sa.String(length=50), server_default='gpt-4o', nullable=False))
    op.add_column('fortune_logs', sa.Column('status', sa.String(length=10), server_default='SUCCESS', nullable=False))
    op.add_column('fortune_logs', sa.Column('raw_prompt', sa.Text(), nullable=False))
    op.add_column('fortune_logs', sa.Column('raw_response', sa.Text(), nullable=True))
    op.add_column('fortune_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('fortune_logs', sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('fortune_logs', sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('fortune_logs', sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('fortune_logs', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('fortune_logs', 'target_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('fortune_logs', 'prompt')
    op.drop_column('fortune_logs', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fortune_logs', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fortune_logs', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('fortune_logs', 'target_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('fortune_logs', 'total_tokens')
    op.drop_column('fortune_logs', 'completion_tokens')
    op.drop_column('fortune_logs', 'prompt_tokens')
    op.drop_column('fortune_logs', 'latency_ms')
    op.drop_column('fortune_logs', 'error_message')
    op.drop_column('fortune_logs', 'raw_response')
    op.drop_column('fortune_logs', 'raw_prompt')
    op.drop_column('fortune_logs', 'status')
    op.drop_column('fortune_logs', 'model_name')
    op.drop_column('daily_fortunes', 'error_msg')
    op.drop_column('daily_fortunes', 'status')
    # ### end Alembic commands ###
