"""add calendar_type

Revision ID: 2039c7a5d784
Revises: 17bbc240bbf3
Create Date: 2026-04-20 20:03:27.817626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2039c7a5d784'
down_revision: Union[str, Sequence[str], None] = '17bbc240bbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_fortunes', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('daily_fortunes', sa.Column('advice', sa.Text(), nullable=False))
    op.add_column('saju_profiles', sa.Column('calendar_type', sa.Enum('SOLAR', 'LUNAR', name='calendartype', native_enum=False), server_default='SOLAR', nullable=False))
    op.add_column('saju_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saju_profiles', 'created_at')
    op.drop_column('saju_profiles', 'calendar_type')
    op.drop_column('daily_fortunes', 'advice')
    op.drop_column('daily_fortunes', 'summary')
    # ### end Alembic commands ###
