"""initial_schema

Revision ID: 97955fa98cae
Revises: 
Create Date: 2026-04-07 18:34:47.821366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97955fa98cae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fortune_phrases',
    sa.Column('phrase_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('mood', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('push_subscriptions',
    sa.Column('sub_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sub_id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_index('idx_push_email', 'push_subscriptions', ['user_email'], unique=False)
    op.create_table('saju_profiles',
    sa.Column('profile_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.String(length=10), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender', native_enum=False), nullable=False),
    sa.Column('year_ganji', sa.String(length=10), nullable=True),
    sa.Column('month_ganji', sa.String(length=10), nullable=True),
    sa.Column('day_ganji', sa.String(length=10), nullable=True),
    sa.Column('time_ganji', sa.String(length=10), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('idx_profiles_email', 'saju_profiles', ['user_email'], unique=False)
    op.create_table('daily_fortunes',
    sa.Column('fortune_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('fortune_score', sa.Integer(), nullable=False),
    sa.Column('money_score', sa.Integer(), nullable=False),
    sa.Column('love_score', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('work_score', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('luck_item', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['saju_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fortune_id'),
    sa.UniqueConstraint('profile_id', 'target_date', name='idx_fortunes_lookup')
    )
    op.create_table('fortune_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['saju_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fortune_logs')
    op.drop_table('daily_fortunes')
    op.drop_index('idx_profiles_email', table_name='saju_profiles')
    op.drop_table('saju_profiles')
    op.drop_index('idx_push_email', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_table('users')
    op.drop_table('fortune_phrases')
    # ### end Alembic commands ###
